name: Run Tests

on: [push]

jobs:
  test_v8.0.3_-_v8.1.0:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Checkout SDK
      uses: actions/checkout@v2
      with:
        repository: julusian/atemsdk
        token: ${{ secrets.ATEMSDK_TOKEN }}
        path: AtemSDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test
      run: |
        $Env:WORKFLOW_VERSION = 'v8.1'
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v8.1/BMDSwitcherAPI.dll /s
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v8.1/BMDSwitcherAPI64.dll /s
        dotnet test LibAtem.MockTests -c Release
  test_v8.1.1_-_v8.1.2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Checkout SDK
      uses: actions/checkout@v2
      with:
        repository: julusian/atemsdk
        token: ${{ secrets.ATEMSDK_TOKEN }}
        path: AtemSDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Test
      run: |
        $Env:WORKFLOW_VERSION = 'v8.1.1'
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v8.1.2/BMDSwitcherAPI.dll /s
        regsvr32 $Env:GITHUB_WORKSPACE/AtemSDK/v8.1.2/BMDSwitcherAPI64.dll /s
        dotnet test LibAtem.MockTests -c Release
